### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by YoavCodes** [blackboardsh/electrobun#2]
> This is a high level roadmap for how we're thinking about building Electrobun over the next few months

- [x] v0.1.0 Core Architecture
  - [x] Initial bun api
  - [x] Initial webview api
  - [x] Initial zig process
  - [x] Initial native bindings for opening a window and webview via objective c
  - [x] RPC
    - [x] RPC between bun and zig
    - [x] RPC between bun and webviews
    - [x] Define RPC Schema types and handlers in typescript
    - [x] Zig promise-like mechanism for waiting for RPC responses
  - [x] Initial electrobun.config format
    - [x] build main process code
    - [x] define and build multiple webview scripts (preload or script tag scripts)
    - [x] copy static assets into the build folder
    - [x] expose built static files via views:// schema
  - [x] native bindings
    - [x] Create a window with a webview
      - [x] load a remote url
      - [x] load inline html
      - [x] load local html, js, css, and other assets defined in electrobun.config via views:// schema
      - [x] define preload scripts via views:// schema
      - [x] add global or webview specific will-navigate handler with ability to allow/block
  - [x] electrobun event emitter, with ability to set, read, and override return values across listeners
  - [x] electrobun cli
    - [x] should build and run your bun and view script files
    - [x] read electrobun.config files
    - [x] build macos bundle
    - [x] wire up log output to terminal
- [ ] v0.2.0 Packaging, signing, and updating
  - [x] Electrobun cli - building locally
    - [x] organize files in the macos app bundle better
    - [x] should build an optimized/minified mac app bundle
    - [x] should install specific versions of bun runtime in a global location and verify checksum when running
    - [x] should handle code signing on osx
    - [x] should create update metadata files
    - [ ] should zip and upload built assets to a server (likely gcloud or github)
  - [ ] electrobun.config
    - [x] configure code signing
    - [ ] configure packaging minification and other settings
    - [ ] configure artifact file upload
    - [x] reads .env file or similar for keys
  - [ ] bun api
    - [x] update logic for developer apps
    - [ ] bun runtime update logic for security updates
- [ ] v0.3.0 Optional Bundled Web Runtime (webview)
  - [ ] pick one, likely chromium embedded framework or similar
  - [ ] match current native webview api with custom webview
    - [ ] open a window and create a webview
    - [ ] support remote url, inline html
    - [ ] preload scripts
    - [ ] will-navigate handler and response
    - [ ] views:// schema
- [ ] v0.4.0 Intel mac builds
  - [ ] build objc, zig, etc. for intel mac
  - [ ] should be able to build Electrobun apps on intel macs
  - [ ] should be able to build Electrobun apps for and distribute to intel macs
- [ ] v0.5.0 API Parity
  - [ ] Build out Electrobun apis to greater coverage compared to Electron and Tauri
  - [ ] Migrate our apps from Electron to Electrobun
- [ ] v0.6.0 Windows Support
- [ ] v0.7.0 Linux Support
- [ ] v0.8.0 Stability
- [ ] v1.0.0 First Stable API                                                                             |

**Comment by TheUltDev** [comment]
You nailed it with the menu / tray apis, so difficult in Tauri.
All I need is a sqlite plugin, stability, remaining platforms, and I'm a lifer.
Great work.

**Comment by YoavCodes** [comment]
Closing this tracking task in favor of using the Project roadmap https://github.com/orgs/blackboardsh/projects/5/views/1
